Attempting with codecov.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -29,34 +29,38 @@ install:
 # - echo "All done."
 
 script:
- # -v2 provides useful information for debugging
- - cabal-$CABALVER configure --enable-tests ${COVOPT} --enable-benchmarks -v2
+  # -v2 provides useful information for debugging
+  - cabal-$CABALVER configure --enable-tests ${COVOPT} --enable-benchmarks -v2
 
- # this builds all libraries and executables
- # (including tests/benchmarks)
- - cabal-$CABALVER build
+  # this builds all libraries and executables
+  # (including tests/benchmarks)
+  - cabal-$CABALVER build
 
- - cabal-$CABALVER test
+  - cabal-$CABALVER test
 
- - bash testit.sh
- - echo "Unit tests successful!"
+  - bash testit.sh
+  - echo "Unit tests successful!"
 
- - cabal-$CABALVER check
+  - cabal-$CABALVER check
 
- # tests that a source-distribution can be generated
- - cabal-$CABALVER sdist
+  # tests that a source-distribution can be generated
+  - cabal-$CABALVER sdist
 
- # check that the generated source-distribution can be built & installed
- - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
-   cd dist/;
-   if [ -f "$SRC_TGZ" ]; then
-      cabal install "$SRC_TGZ";
-   else
-      echo "expected '$SRC_TGZ' not found";
-      exit 1;
-   fi
+  # check that the generated source-distribution can be built & installed
+  - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+    cd dist/;
+    if [ -f "$SRC_TGZ" ]; then
+       cabal install "$SRC_TGZ";
+    else
+       echo "expected '$SRC_TGZ' not found";
+       exit 1;
+    fi
+  - echo $(PWD)
 
 after_script:
+  - echo $(PWD)
+  - travis_retry cabal install codecov-haskell
+  - codecov-haskell [options] [test-suite-names]
   - travis_retry cabal install hpc-coveralls # coverage testing
-  - hpc-coveralls json-autotype-random-test json-autotype-qc-test
+  - hpc-coveralls json-autotype-random-test json-autotype-qc-test || true
 
