Bump base bounds to support GHC 8.0.2. Update Travis.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,67 +1,91 @@
-language: haskell
+# This Travis job script has been generated by a script via
+#
+#   make_travis_yml_2.hs 'json-autotype.cabal'
+#
+# For more information, see https://github.com/hvr/multi-ghc-travis
+#
+language: c
+sudo: false
+
+git:
+  submodules: false  # whether to recursively clone submodules
+
+cache:
+  directories:
+    - $HOME/.cabal/packages
+    - $HOME/.cabal/store
+
+before_cache:
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+  # remove files that are regenerated by 'cabal update'
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx
 
 matrix:
-  allow_failures:
-    - env: GHCVER=7.8.4  CABALVER=1.18 COVOPT=--enable-library-coverage
-    - env: GHCVER=7.6.3  CABALVER=1.18 COVOPT=--enable-library-coverage
-    - env: GHCVER=head   CABALVER=head COVOPT=--enable-coverage
-
-env:
- - GHCVER=7.10.3 CABALVER=1.22 COVOPT=--enable-coverage
- - GHCVER=7.8.4  CABALVER=1.18 COVOPT=--enable-library-coverage
- - GHCVER=7.6.3  CABALVER=1.18 COVOPT=--enable-library-coverage
- - GHCVER=head   CABALVER=head COVOPT=--enable-coverage
+  include:
+    - compiler: "ghc-7.6.3"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks COVOPT=--enable-library-coverage
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-7.6.3], sources: [hvr-ghc]}}
+    - compiler: "ghc-7.8.4"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks COVOPT=--enable-library-coverage
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-7.8.4], sources: [hvr-ghc]}}
+    - compiler: "ghc-7.10.3"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks COVOPT=--enable-coverage
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-7.10.3], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.0.2"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks COVOPT=--enable-coverage
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-8.0.2], sources: [hvr-ghc]}}
 
 before_install:
- - sudo add-apt-repository -y ppa:hvr/ghc
- - travis_retry sudo apt-get update
- - travis_retry sudo apt-get install ghc-$GHCVER cabal-install-$CABALVER
- - travis_retry cabal install cabal-install
- - export PATH=/opt/ghc/$GHCVER/bin:$PATH:$HOME/.cabal/bin
- - echo "Check version again"
- - ghc   --version
- - which cabal
- - cabal --version
+ - HC=${CC}
+ - unset CC
+ - PATH=/opt/ghc/bin:/opt/ghc-ppa-tools/bin:$PATH
+ - PKGNAME='json-autotype'
 
 install:
-  - travis_retry cabal-$CABALVER install --only-dependencies --force-reinstalls --enable-tests
-  #- travis_retry cabal-$CABALVER install --only-dependencies --force-reinstalls --enable-tests ${COVOPT}
+ - cabal --version
+ - echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - BENCH=${BENCH---enable-benchmarks}
+ - TEST=${TEST---enable-tests}
+ - travis_retry cabal update -v
+ - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
+ - rm -fv cabal.project.local
+ - "echo 'packages: .' > cabal.project"
+ - rm -f cabal.project.freeze
+ - cabal new-build -w ${HC} ${TEST} ${BENCH} ${COVOPT} --dep -j2
+ - cabal new-build -w ${HC} --disable-tests --disable-benchmarks --dep -j2
 
-#script:
-# - bash testit.sh
-# - echo "All done."
-
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
 script:
-  # -v2 provides useful information for debugging
-  #- cabal-$CABALVER configure --enable-tests ${COVOPT} --enable-benchmarks -v2
-  - cabal-$CABALVER configure --enable-tests --enable-benchmarks -v2
+ - if [ -f configure.ac ]; then autoreconf -i; fi
+ - rm -rf dist/
+ - cabal sdist # test that a source-distribution can be generated
+ - cd dist/
+ - SRCTAR=(${PKGNAME}-*.tar.gz)
+ - SRC_BASENAME="${SRCTAR/%.tar.gz}"
+ - tar -xvf "./$SRC_BASENAME.tar.gz"
+ - cd "$SRC_BASENAME/"
+## from here on, CWD is inside the extracted source-tarball
+ - rm -fv cabal.project.local
+ - "echo 'packages: .' > cabal.project"
+ # this builds all libraries and executables (without tests/benchmarks)
+ - rm -f cabal.project.freeze
+ - cabal new-build -w ${HC} --disable-tests --disable-benchmarks
+ # this builds all libraries and executables (including tests/benchmarks)
+ # - rm -rf ./dist-newstyle
+ - cabal new-build -w ${HC} ${TEST} ${BENCH}
 
-  # this builds all libraries and executables
-  # (including tests/benchmarks)
-  - cabal-$CABALVER build
-  - find . -iname '*.tix'
-  - find . -iname '*.mix'
-
-  #- cabal-$CABALVER test --keep-tix-files
-  - cabal-$CABALVER test
-  - find . -iname '*.tix'
-
-  - bash testit.sh
-  - echo "Unit tests successful!"
-
-  - cabal-$CABALVER check
-
-  # tests that a source-distribution can be generated
-  - cabal-$CABALVER sdist
-
-  # check that the generated source-distribution can be built & installed
-  - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
-    cd dist/;
-    if [ -f "$SRC_TGZ" ]; then
-       cabal install "$SRC_TGZ";
-    else
-       echo "expected '$SRC_TGZ' not found";
-       exit 1;
-    fi
-  - echo ${PWD}
-
+ # there's no 'cabal new-test' yet, so let's emulate for now
+ - TESTS=( $(awk 'tolower($0) ~ /^test-suite / { print $2 }' *.cabal) )
+ - if [ "$TEST" != "--enable-tests" ]; then TESTS=(); fi
+ - shopt -s globstar;
+   RC=true; for T in ${TESTS[@]}; do echo "== $T ==";
+   if dist-newstyle/build/**/$SRC_BASENAME/**/build/$T/$T; then echo "= $T OK =";
+   else echo "= $T FAILED ="; RC=false; fi; done; $RC
+ - bash testit.sh
+ - echo "Unit tests successful!"
+# EOF
